# Generated by Django 5.2.8 on 2025-11-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_lesson_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="scheduled_at",
            field=models.DateTimeField(default="12.02.2026 12:00"),
        ),
    ]
